# Generated by Django 4.1.1 on 2022-11-01 13:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='account',
            old_name='date_login',
            new_name='date_modified',
        ),
    ]
