# Generated by Django 4.1.1 on 2022-11-02 16:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_rename_date_login_account_date_modified'),
    ]

    operations = [
        migrations.AlterField(
            model_name='account',
            name='email',
            field=models.EmailField(blank=True, db_index=True, max_length=50, null=True, unique=True, verbose_name='Email'),
        ),
    ]
