# Generated by Django 4.1.1 on 2022-11-03 11:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_alter_account_email'),
    ]

    operations = [
        migrations.AddField(
            model_name='account',
            name='role',
            field=models.IntegerField(choices=[(0, 'stuff'), (1, 'student'), (2, 'teacher')], default=1),
        ),
    ]
