# Generated by Django 4.1.1 on 2022-11-05 12:17

import ckeditor.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('course', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='course',
            name='detail',
            field=ckeditor.fields.RichTextField(default='hello'),
            preserve_default=False,
        ),
        migrations.DeleteModel(
            name='CourseDetail',
        ),
    ]
